version: "3.8"

services:
  db:
    container_name: psy_db
    image: postgres:latest
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - dbdata:/var/lib/postgresql/data
    ports:
      - "5435:5432"

  app:
    container_name: psy_app
    build:
      context: .
      dockerfile: Dockerfile
    image: psy_image:latest
    depends_on:
      - db
    volumes:
      - .:/app
    ports:
      - 5000:5005
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app
      - POSTGRES_HOST=postgres
    links:
      - db:postgres

volumes:
  dbdata:
    driver: local